name: Publish to NPM
on:
  push:
    branches:
      - master

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - run: yarn
      - run: yarn build
      - run: sh ./publish.sh
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
